name: TEst action
description: Test Action

inputs:
  run_s2:
    description: Run
    type: boolean
    default: false

runs:
  steps:
    - name: step 1
      shell: bash -euxo pipefail {0}
      run: exit 0
    - name: step 2
      if: false
      shell: bash -euxo pipefail {0}
      run: exit 1
