name: Build

on: 
  workflow_call:
    inputs:
      state:
         description: "lfc state"
         required: true
         type: string
defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  cont:
    runs-on: "ubuntu-latest"
    outputs: 
      conterr: ${{ steps.islfc.outputs.value }}
    steps: 
      - name: is_lfc
        id: islfc
        run: echo value=${{inputs.state == 'lfc' && 'true' || 'false' }} >> "$GITHUB_OUTPUT"
      - name: show
        run: echo ${{steps.islfc.outputs.value }}
  display:
    needs: [cont]
    runs-on: "ubuntu-latest"
    steps:
      - env:
          CONTERR: ${{ needs.cont.outputs.conterr }}
        name: show
        run: echo $CONTERR
      
  build:
    needs: [cont]
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ fromJSON(needs.cont.outputs.conterr) }}
    steps:
      - name: say
        run: echo ${{ inputs.state }}; [ ${{ inputs.state }} != "lfc" ]
