name: Build

on: 
  workflow_call:
    inputs:
      state:
         description: "lfc state"
         required: true
         type: string
defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    runs-on: "ubuntu-latest"
    continue-on-error: true
    steps:
      - name: say
        run: echo ${{ inputs.state }}; [ ${{ inputs.state }} != "lfc" ]
  cover:
    runs-on: "ubuntu-latest"
    needs: [build]
    if: inputs.state == 'lfc' && always()
    steps:
      - name: sayok
        run: exit 0
  
