name: Build

on: 
  workflow_call:
    inputs:
      state:
         description: "lfc state"
         required: true
         type: string
defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  continue:
    runs-on: "ubuntu-latest"
    outputs: 
      conterr: ${{ steps.islfc.value }}
    steps: 
      - name: islfc
        run: echo value=${{inputs.state == 'lfc' && 'true' || 'false' }} >> ${GITHUB_OUTPUT}; 
      
  build:
    needs: [continue]
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ fromJSON(needs.continue.outputs.conterr) }}
    steps:
      - name: say
        run: echo ${{ inputs.state }}; [ ${{ inputs.state }} != "lfc" ]
