name: Build

on: 
  workflow_call:
defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:

  build:
    strategy:
      matrix:
        state: [ lfc, nolfc ]
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ fromJSON(needs.cont.outputs.conterr) }}
    steps:
      - name: uses-lfc
        id: uselfc
        run: echo value=${{ matrix.state == 'lfc' && true || false }} >> $GITHUB_OUTPUT
      - name: say
        continue-on-error: ${{ fromJSON(steps.uselfc.outputs.value) }}
        run: echo ${{ matrix.state }}; [ ${{ matrix.state }} == "lfc" ]
