name: Test
on:
  workflow_dispatch: # adds ability to run this manually
    inputs:
      run_s2:
        description: Run Step2
        required: false
        default: false
        type: boolean
defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: exit 0

      - name: step2
        uses: ./.github/actions/test-multi-steps
        with:
          run_s2: true

  
