name: Test
on:
  workflow_dispatch: # adds ability to run this manually
defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: exit 0

      - name: step2
        if: false
        run: exit 1
  
