name: Test for workflow
on: push
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  regress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg_version: [14, 15, 16]
        no_default_lfc: [true, false]
    steps:
      - name: Show vars
        run: |
          echo pg_version: ${{ matrix.pg_version }}
          echo lfc: ${{ matrix.no_default_lfc }}
    

