name: Test for workflow
on: push
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  build:
    strategy:
      matrix:
        state: [lfc, nolfc]
    uses: ./.github/workflows/build.yml
    with:
      state: ${{ matrix.state }}
  conclusion:
    if: always()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: OK
        run: echo ${{ toJSON(needs.*.result) }}
