name: Test for workflow
on: push
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  test-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        run: exit 1
  conclusion:
    if: always()
    needs: test-fail
    runs-on: ubuntu-latest
    steps:
      - name: OK
        run: exit 0
