name: Test for workflow
on: push
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  regress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg_version: [14, 15, 16]
        no_default_lfc: [false]
        include:
          - pg_version: 16
            no_default_lfc: true
    steps:
      - name: Show vars
        run: |
          echo pg_version: $PG_VERSION
          echo lfc: $NO_DEFAULT_LFC
        env:
          PG_VERSION: ${{ matrix.pg_version }}
          NO_DEFAULT_LFC: ${{ matrix.no_default_lfc }}
    

