name: Test for workflow
on: push
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  build:
    strategy:
      matrix:
        build-type: [release,debug]
    uses: ./.github/workflows/build.yml
    with:
      build-type: ${{matrix.build-type}}
  
  conclusion:
    if: always()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        if: |
          contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled')
          || contains(needs.*.result, 'skipped')
        run: exit 1
