name: Test for workflow
on: push
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  regress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg_version: [14, 15, 16]
        arch: [x64, arm64]
        build_type: [debug, release]
        lfc_state: [with-lfc,without-lfc]
    steps:
      - name: Show vars
        continue-on-error: ${{ matrix.lfc_state == 'with-lfc' && matrix.build_type == 'debug' }}
        run: |
          echo pg_version: $PG_VERSION
          echo build_type: $BUILD_TYPE
          echo lfc: $LFC_STATE
          if [ $LFC_STATE == with-lfc ] && [ $BUILD_TYPE == debug ]; then
            exit 1
          fi
        env:
          PG_VERSION: ${{ matrix.pg_version }}
          LFC_STATE: ${{ matrix.lfc_state }}
          BUILD_TYPE: ${{ matrix.build_type }}
    

