name: Test for workflow
on: push
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  test-fail:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        state: [lfc, nolfc]
    steps:
      - name: Failure
        run: ${state} == "lfc" && exit 1 || exit 0
  conclusion:
    if: always()
    needs: test-fail
    runs-on: ubuntu-latest
    steps:
      - name: OK
        run: exit 0
